sudo: false

language: c

env:
  - GHCVER=7.8.4 CABALVER=head
  - GHCVER=7.10.3 CABALVER=head
  - GHCVER=8.0.1 CABALVER=head
  - GHCVER=8.0.2 CABALVER=head

addons:
  apt:
    sources:
      - hvr-ghc
    packages:
      - ghc-7.8.4
      - ghc-7.10.3
      - ghc-8.0.1
      - ghc-8.0.2
      - cabal-install-head
      - libgmp-dev

install:
  - (mkdir -p $HOME/.local/bin && cd $HOME/.local/bin && wget https://zalora-public.s3.amazonaws.com/tinc && chmod +x tinc)
  - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
  - ghc --version
  - cabal --version
  - travis_retry cabal update
  - sed -i 's/^jobs:/-- jobs:/' ${HOME}/.cabal/config

script:
  - tinc
  - cabal configure --enable-tests --disable-optimization --ghc-options='-Werror'
  - cabal build
  - cabal test

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.tinc/cache
